LINK_PROJETO = "https://www.zahaya.com.br/wp-content/uploads/2022/12"
FORMATO_IMAGEM = 'jpg'
NOME_COLUNA_CONTAGEM_FOTOS = "NUM. FOTOS"
NOME_COLUNA_NOMES_SUBPASTAS = "NOMES_SUBPASTAS"
NOME_COLUNA_NOVOS_NOMES = "NOMES_URL"
NOME_COLUNA_LINKS = "LINKS FOTOS"
NOME_PLANILHA_CONCLUIDA = "Links Adicionados"